### ISSUE TITLE
react_native_safe_area_context issues

### ISSUE THREAD

**Issue by Kasheeram** [duytq94/demo-integrate-react-native#4]
Hi, 
I am not able to build the code, I follow the step as mention in readme file,
Could you please help me!!
Screenshot of issues: https://drive.google.com/file/d/1ICJ6qNAMhIXtrgflE5fe9JEPewX5FRm0/view?usp=sharing

**Comment by mussaiin** [comment]
Hi, @Kasheeram! I think this problem occurs because of linking problems on xCode 12.
I could run this demo project on xCode 12 after some steps like: 

1. Added all this frameworks to _`Link Binary with Libraries`_ inside _`Build Phases`_ of the project. 
<img width="565" alt="Снимок экрана 2021-05-05 в 01 24 20" src="https://user-images.githubusercontent.com/26481400/117058907-07c89f00-ad41-11eb-8ca1-91a99833f30c.png">
<img width="567" alt="Снимок экрана 2021-05-05 в 01 24 25" src="https://user-images.githubusercontent.com/26481400/117059475-a94ff080-ad41-11eb-8242-1d559a4224b6.png">

2. Added this part of code to the end of Podfile.
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
      #Workaround for Xcode 12 and Auto-Linking
      if ['RNCAsyncStorage', 'RNGestureHandler', 'RNReanimated', 'RNScreens', 'RNShare', 'react-native-webview', 'react-native-safe-area-context', 'react-native-netinfo', 'RNVectorIcons'].include?(target.name) #list all affected target in the array
        target.build_phases.each do |build_phases|
          if build_phases.display_name == 'Frameworks'
            file_ref = installer.pods_project.new(Xcodeproj::Project::Object::PBXFileReference)
            file_ref.path = 'React.framework'
            file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
            build_phases.add_file_reference(file_ref)
          end
        end
      end
      if ['react-native-safe-area-context'].include?(target.name)
        target.build_phases.each do |build_phases|
          if build_phases.display_name == 'Frameworks'
            file_ref = installer.pods_project.new(Xcodeproj::Project::Object::PBXFileReference)
            file_ref.path = 'yoga.framework'
            file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
            build_phases.add_file_reference(file_ref)
          end
        end
      end
    end
  end
```

**Comment by duytq94** [comment]
I just update the ios config, please check again.
